site_name: Ansible Tutorial
site_description: My personal notes while I'm learning Ansible

watch: ["docs", "mkdocs.yml", ".overrides"]

repo_url: https://github.com/pejmanS21/ansible-tutorial
repo_name: Ansible Tutorial

theme:
  name: "material"
  icon:
    logo: simple/ansible
    repo: fontawesome/brands/square-github

  # favicon: favicon.ico

  features:
    # - header.autohide
    - navigation.footer
    - content.code.copy
    - toc.follow

  custom_dir: .overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings

# Syntax Highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pejsamadi
      name: Pejman on Twitter

    - icon: fontawesome/brands/github
      link: https://github.com/pejmans21
      name: Pejman on GitHub

extra_css:
  - stylesheets/extra.css
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js

nav:
  - Home: index.md
  - Table of Contents: toc.md
  - About Ansible: about-ansible.md
  - Ansible in Action: ansible-in-action.md

copyright: Copyright &copy; 2023 Pejmans21
