---
- name: Lookup & Pipe collections # read output from a command
  hosts: servers
  tasks:
    - name: raw result of running date command"
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.pipe', 'date') }}"