---
- name: Deploy NodeJS app
  hosts: servers
  tasks:
    - name: Install npm packages
      community.general.npm:
        path: /remote/path/to/dir/contains  # package.json
    
    - name: Start npm app
      command:
        chdir: /remote/path/to/dir/contains # package.json & Code
        cmd: node server
      async: 1000
      poll: 0   # If you want to run multiple tasks in a playbook concurrently, use async with poll set to 0. 
                # When you set poll: 0, Ansible starts the task and immediately moves on to the next task without waiting for a result. 
                # Each async task runs until it either completes, fails or times out (runs longer than its async value). 
                # The playbook run ends without checking back on async tasks.
